Update ESLint config from v4 to v8
MetaMask/eth-hd-keyring pull request #50
Opened 2021-09-16 20:24 UTC by Gudahtt

The ESLint config has been updated a few major versions. The most notable additions are the splitting of the `@metamask/eslint-config` package, `prettier`, the `import` plugin, and semicolons.

The lint npm scripts were updated to match the MetaMask module template.

All lint violates were fixed using `yarn lint:fix`.

2021-09-21 23:39 UTC, rekmarks requested changes

2021-09-21 23:39 UTC, rekmarks commented on .eslintrc.js
>    },
This can be omitted: https://github.com/MetaMask/eslint-config/blob/main/packages/base/src/index.js#L8-L19

2021-09-21 23:45 UTC, Gudahtt commented on .eslintrc.js
>    },
Good catch!

2021-09-21 23:50 UTC, Gudahtt commented on .eslintrc.js
>    },
Fixed in https://github.com/MetaMask/eth-hd-keyring/pull/50/commits/bfd7aa256f28583f2177cb6830f078464971868b

2021-09-22 00:05 UTC, rekmarks approved these changes
LGTM!

2021-09-22 02:37 UTC, merged