Feat/upgrade bip39
MetaMask/eth-hd-keyring pull request #54
Opened 2021-12-30 10:35 UTC by zgayjjf

KeyringController is relying on the latest version of bip39.
Staying the line with KeyringController will somehow reduce the bundle size.

2.x version of bip39 has been out for 4 years.
The latest version, 3.0.4, of bip39 has been out for 8 months.

[KeyringController`s dependency](https://github.com/MetaMask/KeyringController/blob/main/package.json#L34)
[Changelog of bip39](https://github.com/bitcoinjs/bip39/blob/master/CHANGELOG.md)
[Versions of bip39](https://www.npmjs.com/package/bip39)

2021-12-30 10:40 UTC, zgayjjf commented
According to the readme, we will publish this lib to `@metamask/eth-hd-keyring` instead of `eth-hd-keyring`.

However, there is nothing under [@metamask/eth-hd-keyring](https://www.npmjs.com/package/@metamask/eth-hd-keyring) and It will confuse the developer.

We need to publish a new version to fix the problem.

2022-01-04 06:51 UTC, zgayjjf commented
@Gudahtt Do you have time to take a look?

2022-01-04 17:21 UTC, Gudahtt requested changes
Thanks for the contribution! I can approve once the `.gitignore` changes are removed.

2022-01-04 17:21 UTC, Gudahtt commented on .gitignore
> +.idea
Could you remove these changes? They are unrelated to the rest of this PR.

2022-01-04 17:23 UTC, Gudahtt commented
Ignore the "Require Additional Reviewer" CI failures; those are due to a bug in that CI job that has since been fixed. I can fix that separately.

2022-01-05 12:44 UTC, zgayjjf commented on .gitignore
> +.idea
Sure!
I have removed these changes :P

2022-01-05 12:45 UTC, zgayjjf commented
I removed those unrelated changes. Please have another look. @Gudahtt

2022-01-05 13:16 UTC, Gudahtt approved these changes
LGTM, thanks for the contribution!

2022-01-05 14:19 UTC, merged

2022-01-05 14:21 UTC, Gudahtt commented
>We need to publish a new version to fix the problem.

I will be publishing a new version of this package next week. Sorry for the delay, my intent was to publish soon after the package was renamed, but I got side-tracked with other more urgent work.