patch serialize and _initFromMnemonic to account for instances where mnemonic could be buffer array or string
MetaMask/eth-hd-keyring pull request #59
Opened 2022-04-04 18:47 UTC by adonesky1

Adds patch of this package [currently implemented extension side](https://github.com/MetaMask/metamask-extension/blob/develop/patches/eth-hd-keyring%2B3.6.0.patch) to this repo.

2022-04-04 19:43 UTC, mcmire requested changes
Thanks for bringing this over. I think we'd want to update the unit tests before merging this.

2022-04-04 21:28 UTC, Gudahtt commented on index.js
>      const seed = bip39.mnemonicToSeedSync(mnemonic);
I expect this will fail because bip39 always expects a string. We'd need the bip39 patch to merge this. That is, we'll need to fork bip39 first.

2022-04-13 16:25 UTC, mcmire submitted a review, later dismissed
Looks good. The tests could be improved to be more precise, but that's not your fault — I think we can fix that later when we convert them to Jest.

2022-04-13 17:15 UTC, Gudahtt commented on index.js
> +   * as a string, an array of UTF-8 bytes, or a Buffer.
Maybe worth emphasizing here that the array and Buffer types are assumed to be NFKD-normalized: https://github.com/MetaMask/bip39/blob/master/ts_src/index.ts#L72-L73

2022-04-13 17:17 UTC, Gudahtt commented
The `.DS_Store` file should be removed

2022-04-13 18:41 UTC, adonesky1 commented on index.js
> +   * as a string, an array of UTF-8 bytes, or a Buffer.
comment added here: https://github.com/MetaMask/eth-hd-keyring/pull/59/commits/446ba4baa3b4df260023b872409c3fc6d71e9786

2022-04-13 18:41 UTC, adonesky1 commented
> The `.DS_Store` file should be removed

done [here](https://github.com/MetaMask/eth-hd-keyring/pull/59/commits/446ba4baa3b4df260023b872409c3fc6d71e9786)

2022-04-13 19:03 UTC, Gudahtt commented on index.js
> +   * regardless of type should be NFKD normalized.
Strings don't need to be normalized. `@metamask/bip39` still normalizes those for us.

2022-04-13 19:31 UTC, adonesky1 commented on index.js
> +   * regardless of type should be NFKD normalized.
That's true. Will fix.

2022-04-13 19:35 UTC, adonesky1 commented on index.js
> +   * regardless of type should be NFKD normalized.
updated here: https://github.com/MetaMask/eth-hd-keyring/pull/59/commits/c6d58849fffe6062fa3365843a87c33bc5b5611d

2022-04-13 23:57 UTC, Gudahtt approved these changes
LGTM!

2022-04-14 14:33 UTC, merged