integrate MM @scure/bip39 fork once released
MetaMask/eth-hd-keyring pull request #67
Opened 2022-08-23 21:19 UTC by adonesky1

2022-08-23 22:05 UTC, adonesky1 commented on .eslintrc.js
> +      },
https://github.com/mysticatea/eslint-plugin-node/issues/47

2022-09-16 09:10 UTC, kumavis commented on .github/workflows/build-test.yml
> +        node-version: [14.x, 16.x]
add v18

2022-09-16 09:24 UTC, kumavis requested changes
I'd like to see tests that show the generated accounts (eg from 100 SRPs) match those generated by the old library given the same SRP

2022-09-16 09:25 UTC, kumavis commented
@SocketSecurity ignore keccak@3.0.2
@SocketSecurity ignore secp256k1@4.0.3

2022-09-16 17:40 UTC, adonesky1 commented
>I'd like to see tests that show the generated accounts (eg from 100 SRPs) match those generated by the old library given the same SRP

Actually I'm not sure I follow how this has to do with the changes here... We are changing the package that generates the SRPs not logic that derives the accounts

2022-09-16 17:41 UTC, adonesky1 commented
ah I suppose we could compare the derived outputs of `mnemonicToSeedSync`

2022-09-16 23:38 UTC, adonesky1 commented
@kumavis hows this look: https://github.com/MetaMask/eth-hd-keyring/pull/67/commits/69e8e0f1ce370f27adec983865708dfc68b79fa7

2022-09-16 23:42 UTC, adonesky1 commented
The error on node v 18.9.0 is new... not sure about it yet. But will dig in. I am planning to remove `ethereumjs/wallet` (where its thrown) in the next PR also

2022-09-19 19:36 UTC, adonesky1 commented
> The error on node v 18.9.0 is new... not sure about it yet. But will dig in. I am planning to remove ethereumjs/wallet (where its thrown) in the next PR also

yeah so the issue is not introduced in this PR, tests on `main` fail on node v18

2022-09-27 16:21 UTC, kumavis commented
@SocketSecurity ignore secp256k1@4.0.3

2022-09-27 16:25 UTC, kumavis approved these changes
noice

2022-09-27 16:26 UTC, kumavis commented
@SocketSecurity ignore bufferutil@4.0.6
@SocketSecurity ignore utf-8-validate@5.0.9

2022-09-27 16:27 UTC, merged

2022-12-12 22:41 UTC, Gudahtt commented on .eslintrc.js
> +      },
For future reference, we can leave this rule enabled add add `files` to `package.json` instead.

The rule gets confused between production and test modules unless you are explicit about what is published. So far in this package we've been publishing the test files, so the rule assumes they're part of the package, and hence that we've made a mistake by adding modules used in tests as `devDependencies`.

By ensuring the tests aren't published, we resolve the warnings from this rule as well.